#!/bin/bash
# Telegram Bot Setup Guide for Fleet-Ryan

echo "🤖 Telegram Bot Setup for Fleet-Ryan"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Create the bot"
echo "   1. Open Telegram and search for @BotFather"
echo "   2. Send /newbot"
echo "   3. Follow the prompts:"
echo "      - Name: FleetCommander (or your choice)"
echo "      - Username: fleetcommander_bot (must end in 'bot')"
echo "   4. Copy the bot token (looks like: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz)"
echo ""
echo "Step 2: Get your Chat ID"
echo "   1. Send any message to your new bot"
echo "   2. Visit: https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates"
echo "   3. Find your chat ID in the response (looks like: 123456789)"
echo ""
echo "Step 3: Configure the bot"
echo "   1. Edit .env file:"
echo "      TELEGRAM_BOT_TOKEN=<your_token>"
echo "      FLEET_MANAGER_CHAT_ID=<your_chat_id>"
echo ""
echo "Step 4: Set bot commands (optional)"
echo "   Send to @BotFather:"
echo "   /setcommands"
echo "   Then send:"
echo "   status - Get fleet status"
echo "   vehicles - List active vehicles"
echo "   alerts - View active alerts"
echo "   approve - Approve pending request"
echo "   help - Show available commands"
echo ""
echo "Step 5: Disable privacy mode (for group chats)"
echo "   1. Send /setprivacy to @BotFather"
echo "   2. Select your bot"
echo "   3. Select 'Disable'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ After setup, restart the backend:"
echo "   docker-compose restart backend"
echo ""
